apiVersion: v1
kind: Pod
metadata:
  name: esalert-test-pod
spec:
  containers:
    - name: esalert-container
      image: sandeepchowdary/elastalert:1.3
      volumeMounts:
      - name: rule-volume
        mountPath: /etc/esrules

      - name: config-volume
        mountPath: /etc/esconfig/
  volumes:
    - name: rule-volume
      configMap:
        name: rules
    - name: config-volume
      configMap:
        name: esconfig
  restartPolicy: Never
